
class ErrorOrderCreate(Exception):
    pass


class AlreadyRunning(Exception):
    pass
